### ISSUE TITLE
icebearPatch: List symbol

### ISSUE THREAD

**Issue by YannickFricke** [MyRealityCoding/icebearjs#9]
You should add an option for defining a list symbol (like images for every status (added, modified, removed).

**Comment by bitbrain** [comment]
It should be possible via CSS. Each patch item has a proper class defined. To style them do something like:

``` css
li.added { background: url('my-image.png') left center no-repeat; }
```

or do you wish something more specific?
